<a href="https://colab.research.google.com/github/HARISHRAJ-R-07/Mathematical-Statistical-Analysis-for-Data-Science/blob/main/Mathematical_%26_Statistical_Analysis_for_Data_Science.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Module- 3 -Mathematics and Statistics for Data Science

##Assignment 1

##Mathematical & Statistical Analysis for Data Science

A data scientist team needs to evaluate business data before applying advanced predictive
models. To support decision-making, they must use mathematical and statistical techniques to
understand patterns, relationships, and probabilities within the dataset.

###Task 1 – Linear Algebra Implementation

● Perform vector addition, subtraction, and dot product using vector_a and vector_b

● Perform matrix addition and matrix multiplication using matrix_a and matrix_b

● Calculate determinant of matrix_a

● If determinant of matrix_a is not equal to zero, then find inverse of matrix_a

● Compute eigenvalues and eigenvectors of matrix_a

In [1]:
# dataset

import numpy as np
vector_a = np.array([2, 4, 6])
vector_b = np.array([1, 3, 5])
matrix_a = np.array([
[2, 1, 3],
[1, 0, 2],
[4, 1, 1]
])
matrix_b = np.array([
[1, 2, 0],
[3, 1, 4],
[2, 5, 1]
])

In [2]:
print("vector_a :", vector_a)
print("vector_b :", vector_b)

vector_a : [2 4 6]
vector_b : [1 3 5]


In [3]:
 # Perform vector addition, subtraction, and dot product using vector_a and vector_b

vec_add = vector_a + vector_b
vec_sub = vector_a - vector_b
vec_dot = np.dot(vector_a, vector_b)

print("Vector Addition :", vec_add)
print("Vector Subtraction :", vec_sub)
print("Vector Dot Product :", vec_dot)

Vector Addition : [ 3  7 11]
Vector Subtraction : [1 1 1]
Vector Dot Product : 44


In [5]:
print("matrix_a :\n", matrix_a)
print("matrix_b :\n", matrix_b)

matrix_a :
 [[2 1 3]
 [1 0 2]
 [4 1 1]]
matrix_b :
 [[1 2 0]
 [3 1 4]
 [2 5 1]]


In [6]:
# Perform matrix addition and matrix multiplication using matrix_a and matrix_b

mat_add = matrix_a + matrix_b
mat_mul = np.dot(matrix_a, matrix_b)

print("Matrix Addition :\n", mat_add)
print("Matrix Multiplication :\n", mat_mul)

Matrix Addition :
 [[3 3 3]
 [4 1 6]
 [6 6 2]]
Matrix Multiplication :
 [[11 20  7]
 [ 5 12  2]
 [ 9 14  5]]


In [7]:
# Calculate determinant of matrix_a

det_matrix_a = np.linalg.det(matrix_a)

print("Determinant of matrix_a :", det_matrix_a)

Determinant of matrix_a : 6.0


In [9]:
# If determinant of matrix_a is not equal to zero, then find inverse of matrix_a

det_matrix_a = np.linalg.det(matrix_a)

if det_matrix_a != 0:
    inverse_matrix_a = np.linalg.inv(matrix_a)
    print("Inverse of matrix_a :\n", inverse_matrix_a)
    print("Determinant of matrix_a is not equal to zero")
else:
    print("Determinant of matrix_a is equal to zero")

Inverse of matrix_a :
 [[-0.33333333  0.33333333  0.33333333]
 [ 1.16666667 -1.66666667 -0.16666667]
 [ 0.16666667  0.33333333 -0.16666667]]
Determinant of matrix_a is not equal to zero


In [10]:
# Compute eigenvalues and eigenvectors of matrix_a

eigenvalues, eigenvectors = np.linalg.eig(matrix_a)

print("Eigenvalues of matrix_a :", eigenvalues)
print("Eigenvectors of matrix_a :\n", eigenvectors)

Eigenvalues of matrix_a : [ 5.54138127 -2.         -0.54138127]
Eigenvectors of matrix_a :
 [[-0.66037269 -0.42163702  0.17485589]
 [-0.3575134  -0.52704628 -0.96894315]
 [-0.66037269  0.73786479  0.17485589]]


### Task 2 – Probability Concepts

####Using Python / NumPy / SciPy:
● Calculate probability of successful sales

● Demonstrate conditional probability using customer segments

In [11]:
# Dataset

sales_success = [0.65, 0.35]
customer_segments = ["Premium", "Regular"]
segment_purchase_probability = {
"Premium": 0.80,
"Regular": 0.50
}

sales_success

[0.65, 0.35]

In [12]:
# Calculate probability of successful sales

total_sales = sum(sales_success)
probability_success = [success / total_sales for success in sales_success]

print("Probability of Successful Sales:")
for i in range(len(customer_segments)):
    print(f"{customer_segments[i]}: {probability_success[i]}")


Probability of Successful Sales:
Premium: 0.65
Regular: 0.35


In [14]:
print("Or :")

# Probability of successful sales
prob_success = sales_success[0]

print("Probability of successful sales:", prob_success)
print("Successful sales percentage:", prob_success * 100, "%")

Or :
Probability of successful sales: 0.65
Successful sales percentage: 65.0 %


In [15]:
# Demonstrate conditional probability using customer_segments

import numpy as np
from scipy import stats


print("\nConditional Probability:")

# Premium customers
premium = segment_purchase_probability["Premium"]
print("P(Purchase | Premium):", premium)
print("Premium purchase percentage:", premium * 100, "%")

# Regular customers
regular = segment_purchase_probability["Regular"]
print("P(Purchase | Regular):", regular)
print("Regular purchase percentage:", regular * 100, "%")



Conditional Probability:
P(Purchase | Premium): 0.8
Premium purchase percentage: 80.0 %
P(Purchase | Regular): 0.5
Regular purchase percentage: 50.0 %


###Bayes’ theorem :

● Apply Bayes’ theorem to calculate updated probability of a customer purchase

○ Formula: P(A|B) = [P(B|A) * P(A)] / P(B)

In [16]:
# Data for Bayes’ theorem :

# Probability Dataset for Customer Purchase Analysis

# P(A): Probability that a customer is Premium
P_A = 0.40
# P(B): Probability that a customer makes a purchase
P_B = 0.62
# P(B|A): Probability that a Premium customer makes a purchase
P_B_given_A = 0.80

# P(A|B) = [P(B|A) * P(A)] / P(B)

P_A_given_B = (P_B_given_A * P_A) / P_B

print("Updated Probability of a Customer Purchase (P(A|B)):", P_A_given_B)
print("Updated purchase percentage:", P_A_given_B * 100, "%")

Updated Probability of a Customer Purchase (P(A|B)): 0.5161290322580646
Updated purchase percentage: 51.61290322580646 %


###Binomial distribution : (for 20 trials)


● Generate a normal distribution and uniform distribution for the following parameters

In [19]:
# Simulate a binomial distribution for 20 trials

# Binomial Distribution Parameters - n = number of trials, p = probability of success
n_trials = 20
success_prob = 0.65

binomial_distribution = np.random.binomial(n_trials, success_prob)
binomial_distribution

15

In [24]:
# Generate a normal distribution and uniform distribution for the following parameters

normal_distribution = np.random.normal(loc=0, scale=1, size=10)
uniform_distribution = np.random.uniform(low=0, high=1, size=10)

print("Normal Distribution:")
print(normal_distribution)
print("\nUniform Distribution:")
print(uniform_distribution)

Normal Distribution:
[ 0.32351738  3.57498399 -0.60989812  1.67083786  1.30304509 -0.24348645
 -0.62048269 -0.41908403  0.12945279  1.57293072]

Uniform Distribution:
[0.14115895 0.43744003 0.06682256 0.87023487 0.38698072 0.53766071
 0.88345953 0.41340613 0.75972924 0.60479102]


### Normal distribution and Uniform distribution

In [23]:
# Generate a normal distribution and uniform distribution for the following parameters

# Distribution Parameters
normal_mean = 50
normal_std = 10
uniform_low = 0
uniform_high = 1

normal_distribution = np.random.normal(loc=normal_mean, scale=normal_std, size=10)
uniform_distribution = np.random.uniform(low=uniform_low, high=uniform_high, size=10)

print("Normal Distribution:")
print(normal_distribution)
print("\nUniform Distribution:")
print(uniform_distribution)



Normal Distribution:
[53.24970393 55.17466848 49.70575988 48.80779151 50.23539877 36.00679961
 64.36191651 62.3829828  55.69287009 53.08563884]

Uniform Distribution:
[0.58660507 0.78289628 0.15016426 0.05661042 0.53197831 0.71376378
 0.38152534 0.16118162 0.99906808 0.08492081]


### Task 3 – Descriptive Statistics

● Compute mean, median, and mode of sales_data

● Calculate range, variance, and standard deviation

● Measure skewness and kurtosis

● Interpret whether the dataset is symmetric, positively skewed, or negatively skewed

In [26]:
# Statistical Dataset

sales_data = [120, 135, 150, 145, 160, 155, 170, 165, 180, 175,
190, 200, 210, 195, 185, 175, 165, 155, 145, 135]

print(sales_data)

[120, 135, 150, 145, 160, 155, 170, 165, 180, 175, 190, 200, 210, 195, 185, 175, 165, 155, 145, 135]


In [28]:
# Compute mean, median, and mode of sales_data

mean_sales = np.mean(sales_data)
median_sales = np.median(sales_data)
mode_sales = stats.mode(sales_data)

print("Mean of sales_data:", mean_sales)
print("Median of sales_data:", median_sales)
print("Mode of sales_data:", mode_sales)

Mean of sales_data: 165.5
Median of sales_data: 165.0
Mode of sales_data: ModeResult(mode=np.int64(135), count=np.int64(2))


In [32]:
# Calculate range, variance, and standard deviation

range_sales = np.max(sales_data) - np.min(sales_data)
variance_sales = np.var(sales_data)
std_sales = np.std(sales_data)

print("Range of sales_data:", range_sales)
print("Variance of sales_data:", variance_sales)
print("Standard Deviation of sales_data:", std_sales)

Range of sales_data: 90
Variance of sales_data: 534.75
Standard Deviation of sales_data: 23.124662159694356


In [33]:
# Measure skewness and kurtosis

skewness_sales = stats.skew(sales_data)
kurtosis_sales = stats.kurtosis(sales_data)

print("Skewness of sales_data:", skewness_sales)
print("Kurtosis of sales_data:", kurtosis_sales)

Skewness of sales_data: 0.030143346252736614
Kurtosis of sales_data: -0.7069943289224954


In [34]:
# Using NumPy / Pandas / statistics library:

# Interpret whether the dataset is symmetric, positively skewed, or negatively skewed

symmetrickness_sales = stats.skew(sales_data)
positive_skewness = symmetrickness_sales > 0
negative_skewness = symmetrickness_sales < 0

print("Symmetricity of sales_data:", symmetrickness_sales)
print("Is sales_data positively skewed?", positive_skewness)
print("Is sales_data negatively skewed?", negative_skewness)

Symmetricity of sales_data: 0.030143346252736614
Is sales_data positively skewed? True
Is sales_data negatively skewed? False
